apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - "./mysql/deployment.yaml"
  - "./mysql/service.yaml"
  - "./mysql/pvc.yaml"
  - "./aspnet-app/deployment.yaml"
  - "./aspnet-app/service.yaml"

configMapGenerator:
- name: mysql-cnf
  behavior: create
  files:
  - "./mysql/custom.cnf"
- name: shared-config
  literals:
  - MYSQL_USER="aspnet"
  - MYSQL_DATABASE="aspnet"
  - MYSQL_SERVER="mysql"
- name: aspnet-env
  behavior: create
  envs:
  - "./aspnet-app/aspnet.env"

# sealed-secrets adapted from https://faun.pub/sealing-secrets-with-kustomize-51d1b79105d8
# make sealed-secrets to use name of the secrets with hash value
# configurations:
#   - kustomizationconfig/sealed-secret.yaml

# secretGenerator:
#   - name: mysql-root
#     type: Opaque
#     options:
#       annotations:
#         "sealedsecrets.bitnami.com/managed": "true"
#       disableNameSuffixHash: true
#   - name: shared-secret
#     type: Opaque
#     options:
#       annotations:
#         "sealedsecrets.bitnami.com/managed": "true"
#       disableNameSuffixHash: true