apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


namespace: ci-test
nameSuffix: -ci-test

commonLabels:
  trash2gather.at/stage: ci-test

resources:
- ../base
- mysql-root.sealed.yaml
- sharedSecret.sealed.yaml
- ingress.yaml


configMapGenerator:
- behavior: merge
  envs:
  - ./aspnet.env
  name: aspnet-env

patchesStrategicMerge:
- |-
  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: aspnet
  spec:
    template:
      spec:
        containers:
        - name: aspnet
          env:
          - name: MYSQLCONNSTR_DNSDatabase
            value: "server=$(MYSQL_SERVER);port=3306;database=$(MYSQL_DATABASE);user=$(MYSQL_USER);password=$(MYSQL_PASSWORD)"

replacements:
- source:
    fieldPath: metadata.name
    kind: Service
    name: mysql
    version: v1
  targets:
  - fieldPaths:
    - data.MYSQL_SERVER
    select:
      kind: ConfigMap
      name: shared-config
      version: v1
- source:
    fieldPath: spec.template.metadata.name
    group: bitnami.com
    kind: SealedSecret
    name: mysql-root
    version: v1alpha1
  targets:
  - fieldPaths:
    - metadata.name
    select:
      group: bitnami.com
      kind: SealedSecret
      name: mysql-root
      version: v1alpha1
- source:
    fieldPath: spec.template.metadata.name
    group: bitnami.com
    kind: SealedSecret
    name: shared-secret
    version: v1alpha1
  targets:
  - fieldPaths:
    - metadata.name
    select:
      group: bitnami.com
      kind: SealedSecret
      name: shared-secret
      version: v1alpha1


images:
- name: someRepo/aspnet-image
  newName: gapodo/aspnet-test
  newTag: 2088602942-1
