apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../base

namespace: ci-test
nameSuffix: -ci-test

commonLabels:
  trash2gather.at/stage: ci-test

resources:
- mysql-root.sealed.yaml
- sharedSecret.sealed.yaml
- ingress.yaml

configMapGenerator:
- name: aspnet-env
  behavior: merge
  envs:
  - "./aspnet.env"

patchesStrategicMerge:
- |-
  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: aspnet
  spec:
    template:
      spec:
        containers:
        - name: aspnet
          env:
          - name: MYSQLCONNSTR_DNSDatabase
            value: "server=$(MYSQL_SERVER);port=3306;database=$(MYSQL_DATABASE);user=$(MYSQL_USER);password=$(MYSQL_PASSWORD)"

replacements:
- source:
    version: v1
    kind: Service
    name: mysql
    fieldPath: metadata.name
  targets:
  - select:
      version: v1
      kind: ConfigMap
      name: shared-config
    fieldPaths:
    - data.MYSQL_SERVER
# - source:
#     version: v1
#     kind: Service
#     name: mysql
#     fieldPath: metadata.name
#   targets:
#   - select:
#       version: v1
#       kind: Service
#       name: mysql
#     fieldPaths:
#     - spec.selector.app
- source:
    group: bitnami.com
    version: v1alpha1
    kind: SealedSecret
    name: mysql-root
    fieldPath: spec.template.metadata.name
  targets:
  - select:
      group: bitnami.com
      version: v1alpha1
      kind: SealedSecret
      name: mysql-root
    fieldPaths:
    - metadata.name
- source:
    group: bitnami.com
    version: v1alpha1
    kind: SealedSecret
    name: shared-secret
    fieldPath: spec.template.metadata.name
  targets:
  - select:
      group: bitnami.com
      version: v1alpha1
      kind: SealedSecret
      name: shared-secret
    fieldPaths:
    - metadata.name


images:
  - name: someRepo/aspnet-image
    newName: "gapodo/aspnet-test"
    newTag: "2088602942-1"
